version: "3.7"
services:
  youtube-dl:
    build: .
    volumes:
      - ./files/:/usr/src/app/files/
    networks:
      - youtube-dl-network
networks:
  youtube-dl-network:
    name: youtube-dl-network
    driver: bridge
